import "primereact/resources/themes/lara-light-cyan/theme.css";
import "@/styles/globals.css";

import { Provider } from "./provider";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "@/trpc/react";


export const metadata = {
  title: "Bicycle Admin",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" >
      <body>
        <TRPCReactProvider cookies={cookies().toString()}>
          <Provider>
            {children}
          </Provider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
